project_id = "xdinlkmqmjlrmunsjswf"

[functions.process-order]
verify_jwt = true

[functions.initialize-balance]
verify_jwt = true

[functions.update-market-data]
verify_jwt = false

[functions.birdeye-proxy]
verify_jwt = false

[functions.admin-2fa]
verify_jwt = true

[functions.api-key-rotation]
verify_jwt = true

[functions.financial-audit-log]
verify_jwt = false

[functions.generate-data-export]
verify_jwt = true

[functions.ai-trading-assistant]
verify_jwt = false

[functions.competition-scoring]
verify_jwt = false

[functions.content-moderation]
verify_jwt = true

[functions.copy-trading-engine]
verify_jwt = true

[functions.enhanced-auth]
verify_jwt = false

[functions.generate-agent-logo]
verify_jwt = true

[functions.health-check]
verify_jwt = false

[functions.market-news-sentiment]
verify_jwt = false

[functions.platform-metrics]
verify_jwt = true

[functions.realtime-market-data]
verify_jwt = false

[functions.realtime-session]
verify_jwt = false

[functions.security-middleware]
verify_jwt = false

[functions.security-monitoring]
verify_jwt = true

[functions.wallet-auth]
verify_jwt = false

[functions.migrate-portfolio]
verify_jwt = true

[functions.send-notification]
verify_jwt = true

[functions.defi-operations]
verify_jwt = true

[functions.staking-operations]
verify_jwt = true

[functions.defi-rewards-calculator]
verify_jwt = false

[functions.defi-pool-sync]
verify_jwt = false

[functions.ai-chat]
verify_jwt = true

[functions.create-agent]
verify_jwt = true

[functions.acp-create-service]
verify_jwt = true

[functions.acp-create-job]
verify_jwt = true

[functions.acp-process-transaction]
verify_jwt = true

[functions.generate-trading-signal]
verify_jwt = true

[functions.process-price-alert]
verify_jwt = false

[functions.process-notifications]
verify_jwt = false

[functions.queue-notification]
verify_jwt = false

[functions.get-notification-stats]
verify_jwt = false

[functions.analytics-aggregator]
verify_jwt = false

[functions.sentiment-analyzer]
verify_jwt = false

[functions.trend-detector]
verify_jwt = false

[functions.anomaly-detector]
verify_jwt = false

[functions.analytics-query]
verify_jwt = false