project_id = "xdinlkmqmjlrmunsjswf"

[functions.realtime-session]
verify_jwt = false

[functions.security-middleware]
verify_jwt = false

[functions.admin-2fa]
verify_jwt = true

[functions.enhanced-auth]
verify_jwt = false

[functions.security-monitoring]
verify_jwt = true

[functions.ai-trading-assistant]
verify_jwt = false

[functions.realtime-market-data]
verify_jwt = false