project_id = "xdinlkmqmjlrmunsjswf"

[functions.security-middleware]
verify_jwt = false

[functions.admin-2fa]
verify_jwt = true

[functions.enhanced-auth]
verify_jwt = false

[functions.security-monitoring]
verify_jwt = true